//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalBookingDetail
    {
        public int AdditionalBookingDetailsID { get; set; }
        public Nullable<int> BookingGuestId { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<int> GuestID { get; set; }
    
        public virtual ServiceList ServiceList { get; set; }
        public virtual BookingGuest BookingGuest { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
