//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingGuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingGuest()
        {
            this.AdditionalBookingDetails = new HashSet<AdditionalBookingDetail>();
        }
    
        public int BookingGuestID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalBookingDetail> AdditionalBookingDetails { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
