//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.AdditionalBookingDetails = new HashSet<AdditionalBookingDetail>();
            this.BookingGuests = new HashSet<BookingGuest>();
        }
    
        public int GuestID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string GuestName { get; set; }
        public string Email { get; set; }
        public string AddressDetail { get; set; }
        public string StateName { get; set; }
        public string AadhaarNumber { get; set; }
        public string MobileNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalBookingDetail> AdditionalBookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingGuest> BookingGuests { get; set; }
    }
}
