//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> HSN_SAC_Code { get; set; }
        public Nullable<decimal> Line_Total { get; set; }
        public string GST_Number { get; set; }
        public Nullable<int> SGST { get; set; }
        public Nullable<int> CGST { get; set; }
        public Nullable<int> IGST { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ServiceList ServiceList { get; set; }
        public virtual Room Room { get; set; }
    }
}
