//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> paidAmount { get; set; }
        public Nullable<System.DateTime> PaymentCreatedAt { get; set; }
        public Nullable<System.DateTime> PaymentUpdatedAt { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
