//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prop
    {
        public int PropID { get; set; }
        public string Names { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
